// Generated by Xata Codegen 0.21.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "example",
    columns: [
      {
        name: "Entity",
        type: "string",
        notNull: true,
        defaultValue: "unknown",
      },
      { name: "Title", type: "string" },
      { name: "Name", type: "string", unique: true },
      { name: "Geo", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Example = InferredTypes["example"];
export type ExampleRecord = Example & XataRecord;

export type DatabaseSchema = {
  example: ExampleRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Praveen-K-M-s-workspace-5ubi9b.us-east-1.xata.sh/db/example-app-database",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
